name: NeXora Backend Deployment

on:
  workflow_dispatch:

jobs:
  build:
    name: Build NestJS Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexora-backend
          path: .

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: nexora-backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C17B2D1929DE4C69AF8984EFCE05B07B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BA387039FA0342FAA0536697E317C453 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_434A6B23E212467289C98210D5124717 }}

      - name: Deploy NeXora Backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-nexora'
          slot-name: 'Production'
          package: .